apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-1121485
  labels:
    app: spring-1121485
spec:
  replicas: 1
  selector:
       matchLabels:
         app: spring-1121485
  template:
    metadata:
      name: spring-1121485
      labels:
        app: spring-1121485
    spec:
      containers:
      - name: spring-1121485
        image: prabhat2020/testing4:latest
        resources:
          limits:
            memory: 1Gi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
  selector:
    matchLabels:
      app: spring-1121485

---

apiVersion: v1
kind: Service
metadata:
  name: spring-1121485
spec:
  selector:
    app: spring-1121485
  ports:
    - port: 8080
  type: LoadBalancer
